ember-config {
    host = 0.0.0.0
    port = 4041
}

postgres-config {
    n-threads = 8
    url = "jdbc:postgresql:board"
    user = "docker"
    pass = "docker"
}

security-config {
    secret = "secret"
    jwt-expiry-duration = "1 day"
}

email-service-config {
    host = "smtp.ethereal.email",
    port = 587,
    user = "ervin.olson@ethereal.email",
    pass = "7jktTffjasT4efqEsg",
    frontend-url = "https://google.com"
}

token-config {
    token-duration = 600000
}

stripe-config {
    price = "price_1TXT3pCmWFBchYXh5Nn3DNsz"
    key = "sk_test_51TXQQRCmWFBchYXhMWN5HsfpMDCyRWSGIvNCkYW4knV80EfI70foStaw7PWXKuxxcWUoxamWXDEP6jJdMLl2AMmm00Yh3j5jP2"
    success-url = "http://localhost:1234/jobs"
    cancel-url = "http://localhost:1234"
}